default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: appointmentdatabase
  username: kidd
  password: eunbeb
  host: localhost
  port: 5432

test:
  <<: *default
  database: appointmentdatabase
  username: kidd
  password: eunbeb
  host: localhost
  port: 5432

production:
  <<: *default
  database: appointmentdatabase
  username: kidd
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432
